In [116]:
from google.cloud import storage
from os.path import join, dirname
from dotenv import load_dotenv
import os
from oauth2client.service_account import ServiceAccountCredentials
from PIL import Image
import requests
from io import BytesIO


In [22]:
#credentials = ServiceAccountCredentials.from_json_keyfile_dict(credentials_dict)

In [25]:
from google.oauth2 import service_account

target_audience = 'https://console.cloud.google.com/storage/browser/bucket-covid-19'

creds = service_account.IDTokenCredentials.from_service_account_file(
        '../batch-606-covid-19-5d766c13ace0.json',
        target_audience=target_audience)

In [102]:
def get_files_from_storage(file_names):
    #get files from google storage
    images = []
    if len(file_names)>0:
        for file_name in file_names:
            storage_client = storage.Client.from_service_account_json(json_credentials_path='batch-606-covid-19-5d766c13ace0.json')
            bucket = storage_client.get_bucket('bucket-covid-19')
            blob = bucket.blob(file_name)
            images.append(blob)
        return images 
    else:
        return None

In [99]:
file_name = 'CT_image_test.png'

In [55]:
img_PIL = Image.open('some images/IMG-0001-00088.png')
img_PIL.show()

In [66]:
def call_prediction(image_name):
    url = 'https://covid-ct-predictions-1-3sowdrohva-ew.a.run.app/predict'
    params = {'file_names':image_name}
    result = requests.get(url = url, params = params)
    return result

In [109]:
y = ['image_number(7567).jpg']
x = get_files_from_storage(y)

In [110]:
var = x[0]

In [137]:
v = var.download_to_filename('temp.jpeg')


In [141]:
cv2.imread('temp.jpeg')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [ ]:
c=np.array([read_ct_img_bydir('temp.jpeg')])[:,:,:,np.newaxis]

In [114]:
from io import BytesIO

imag = Image.open(BytesIO(v))

In [138]:
import numpy as np
np.load(v)

TypeError: expected str, bytes or os.PathLike object, not NoneType

In [117]:
type(imag)

PIL.JpegImagePlugin.JpegImageFile

In [143]:
def preproc_before_pred(img):
    img=cv2.imread(img)
    img=cv2.cvtColor(img, cv2.IMREAD_GRAYSCALE)
    img=cv2.resize(img,(200,200))
    return img

In [181]:
def read_ct_img_bydir(target_dir):
    img=cv2.imdecode(np.fromfile(target_dir,dtype=np.uint8),cv2.IMREAD_GRAYSCALE)
    #img = corp_margin(img)
    img=cv2.resize(img,(200,200))
    
    return img

In [144]:
import cv2

preproc_before_pred('temp.jpeg')

array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0

In [179]:
pwd

'/Users/eitannir/code/Eitanni/NinLev/Covid_19'

In [183]:
j = read_ct_img_bydir('image_number(7567).jpg')

In [156]:
cd models

/Users/eitannir/code/Eitanni/NinLev/Covid_19/models


In [162]:
cd ..

/Users/eitannir/code/Eitanni/NinLev/Covid_19/models


In [187]:
pwd

'/Users/eitannir/code/Eitanni/NinLev/Covid_19'

In [168]:
from tensorflow.keras.models import load_model

loaded_model = load_model('salem') # load model


In [185]:
c=np.array([read_ct_img_bydir('temp.jpeg')])[:,:,:,np.newaxis]

In [186]:
loaded_model.predict(c)

array([[9.9856621e-01, 3.8794637e-06, 1.4299087e-03]], dtype=float32)

In [56]:
image_name = 'CT_image_test.png'

In [67]:
call_prediction(image_name)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)